### ISSUE TITLE
Unnecessary type-raising

### ISSUE THREAD

**Issue by kovvalsky** [ParallelMeaningBank/easyccg#2]
I tried the newer version but the following still remains:

It seems that --unrestrictedRules flag is buggy.
Both sentences get same supertags but different derivations: (1) gets `an anchor` type raised.
(1) `Every ship needs an anchor .`
(2) `Every sheep needs an anchor .`

Since the parser is supertag-factored this should not happend, right?
```
$ echo "Every ship needs an anchor ." | java -jar easyccg.jar --model /net/gsb/pmb/retrain/parse/en.model/ --outputFormat boxer -s
Loading model...
Parsing...
:- op(601, xfx, (/)).
:- op(601, xfx, (\)).
:- multifile ccg/2, id/2.
:- discontiguous ccg/2, id/2.

ccg(1,
 ba(s:dcl,
  fa(np,
   t(np/n, 'Every', [lemma:'every']),
   t(n, 'ship', [lemma:'ship'])),
  ba(s:dcl\np,
   t((s:dcl\np)/np, 'needs', [lemma:'needs']),
   rp((s:X\np)\((s:X\np)/np),
    lx((s:X\np)\((s:X\np)/np), np,
     fa(np,
      t(np/n, 'an', [lemma:'an']),
      t(n, 'anchor', [lemma:'anchor']))),
    t(., '.', [lemma:'.']))))).

Coverage: 100%
Sentences parsed: 1
Speed: 11.63 sentences per second

$ echo "Every sheep needs an anchor ." | java -jar easyccg.jar --model /net/gsb/pmb/retrain/parse/en.model/ --outputFormat boxer -s
Loading model...
Parsing...
:- op(601, xfx, (/)).
:- op(601, xfx, (\)).
:- multifile ccg/2, id/2.
:- discontiguous ccg/2, id/2.

ccg(1,
 ba(s:dcl,
  fa(np,
   t(np/n, 'Every', [lemma:'every']),
   t(n, 'sheep', [lemma:'sheep'])),
  fa(s:dcl\np,
   t((s:dcl\np)/np, 'needs', [lemma:'needs']),
   rp(np,
    fa(np,
     t(np/n, 'an', [lemma:'an']),
     t(n, 'anchor', [lemma:'anchor'])),
    t(., '.', [lemma:'.']))))).

Coverage: 100%
Sentences parsed: 1
Speed: 8.85 sentences per second
```

**Comment by texttheater** [comment]
Fixed a bug in the implementation of the normal-form constraints in fece7f7. `Every ship needs an anchor .` no longer receives the non-normal-form derivation.

I think that was the whole issue. The `--unrestrictedRules` flag just uncovered it. And I’m not sure, but to my knowledge the supertag-factoring does not rule out different derivations with the same supertag sequence. The input to the A* algorithm is a probability distribution over categories for each word. It might be that for different distributions it finds different derivations that happen to have the same supertag sequence.
