### ISSUE TITLE
No derivations over reflexive categories (S\NP)/((S\NP)/NP)

### ISSUE THREAD

**Issue by kovvalsky** [ParallelMeaningBank/easyccg#4]
`echo "We|NP helped|(S[dcl]\NP)/NP each~other|(S[dcl]\NP)\((S[dcl]\NP)/NP) .|S[dcl]\S[dcl]"  | java -jar ext/easyccg/easyccg.jar  --model retrain/parse/en.model --unrestrictedRules --rootCategories S[dcl] S[wq] S[q] NP S[b]\\NP S[intj] --outputFormat boxer --inputFormat constrained`

`FAILED TO PARSE! We helped each~other .`

`(S[dcl]\NP)/NP` & `(S[dcl]\NP)\((S[dcl]\NP)/NP)` combination also requires --unrestrictedRules as the construction with these categories was not found in CCGbank. 

P.S. We just discovered it before the PMB release.

**Comment by kovvalsky** [comment]
Also CCGweb doesn't like it
![ccgweb](https://user-images.githubusercontent.com/12584294/34249897-93b40534-e63b-11e7-87fb-f63559cc6d29.png)

**Comment by kovvalsky** [comment]
Also ccgweb doesnt like that
![ccgweb](https://user-images.githubusercontent.com/12584294/34249995-d4a5d4e6-e63b-11e7-9218-5094d6d9565f.png)

**Comment by texttheater** [comment]
Yes, that is because EasyCCG thinks `(S\NP)\((S\NP)/NP)` is type-raised and therefore doesn’t allow it to apply (normal-form constraint).

In CCGrebank reflexive pronouns are just `NP`. Why do you want them to be `(S\NP)\((S\NP)/NP)` instead?

**Comment by kovvalsky** [comment]
Because of semantics. Lexical semantics for such categories will be different from type-raised NPs. The semantics of the former will have equality that makes subject and object the same.

**Comment by texttheater** [comment]
I see. I think the solution is to make EasyCCG only treat categories as type-raised when a type-raising rule was actually used to create them. I’ll look into that.
