### ISSUE TITLE
How does the span constraint functionality work?

### ISSUE THREAD

**Issue by kovvalsky** [ParallelMeaningBank/easyccg#7]
How do I pass the span cosntraints to the parser?

**Comment by texttheater** [comment]
Use parentheses, e.g.:

    echo "He| saw| the| ( girl| with| the| telescope| ) .|" | java -jar git/easyccg/easyccg.jar --model git/ccgweb/models/parse/eng.model  --outputFormat boxer --unrestrictedRules -i constrained
